
# for the moment, tailored to LIMITS results
# topN: omit the N top abundant species from evaluation (to avoid explosion problems)
compareOriAndPred<-function(input.folder.ori="", input.folder.pred="", output.folder="", predictor="limits", expIds=c(), topN=0){

  output.subfolder=""
  resultStr=""

  if(input.folder.ori != ""){
    if(!file.exists(input.folder.ori)){
      stop(paste("The input folder for the ori data ",input.folder.ori,"does not exist!"))
    }
    input.settings.folder=paste(input.folder.ori,"settings",sep="/")
    if(!file.exists(input.settings.folder)){
      stop("The input folder with ori data does not have a settings subfolder!")
    }
    input.timeseries.folder=paste(input.folder.ori,"timeseries",sep="/")
    if(!file.exists(input.settings.folder)){
      stop("The input folder with ori data does not have a time series subfolder!")
    }
  }else{
    stop("Please provide the input folder for the original time series and settings!")
  }

  if(output.folder != ""){
    if(!file.exists(output.folder)){
      stop(paste("The output folder ",output.folder,"does not exist!"))
    }
  }

  if(input.folder.pred != ""){
    if(!file.exists(input.folder.pred)){
      stop(paste("The input folder for the predicted data ",input.folder.pred,"does not exist!"))
    }
  }else{
    stop("Please provide the input folder for the predictions!")
  }

  # loop experiments
  for(expId in expIds){
    print(paste("Processing identifier",expId))

    input.settings.name=paste(expId,"settings",sep="_")
    input.settings.expId.folder=paste(input.settings.folder,input.settings.name,sep="/")
    if(!file.exists(input.settings.expId.folder)){
      stop("The input settings folder does not have a subfolder for the input experiment identifier!")
    }
    input.timeseries.name=paste(expId,"timeseries",sep="_")
    input.timeseries.expId.folder=paste(input.timeseries.folder,input.timeseries.name,sep="/")
    if(!file.exists(input.timeseries.expId.folder)){
      stop("The input time series folder does not have a subfolder for the input experiment identifier!")
    }

    # read settings file
    input.settings.expId.file=paste(expId,"settings.txt",sep="_")
    settings.path=paste(input.settings.expId.folder,input.settings.expId.file,sep="/")
    if(!file.exists(settings.path)){
      stop(paste("The settings file",settings.path,"does not exist!"))
    }

    # read time series file
    ts.name=paste(expId,"timeseries.txt",sep="_")
    input.path.ts=paste(input.timeseries.expId.folder,ts.name,sep="/")
    print(paste("Reading original time series from:",input.path.ts,sep=" "))
    ts=read.table(file=input.path.ts,sep="\t",header=FALSE)
    ts=as.matrix(ts)

    source(settings.path)

    # create subfolder
    if(output.folder != ""){
      subfolder.name=paste(expId, predictor, sep="_")
      output.subfolder=paste(output.folder, subfolder.name, sep="/")
      if(!file.exists(output.subfolder)){
        dir.create(output.subfolder)
      }
    }

    # prepare reading predicted files
    expId.pred.name=paste(expId,"timeseries",sep="_")
    pred.expId.folder=paste(input.folder.pred,expId.pred.name,sep="/")

    # read predicted time series
    expId.pred.ts.name=paste(expId,"timeseries","ts.txt",sep="_")
    expId.pred.ts.path=paste(pred.expId.folder,expId.pred.ts.name,sep="/")
    tspred=read.table(file=expId.pred.ts.path,header=FALSE)
    tspred=t(as.matrix(tspred))

    Agenerator=FALSE
    keep=c()

    # read interaction matrix if one was generated by fitting routine
    if(predictor=="limits"){

      # normalize original time series (because Limits was run on normalized time series)
      ts=normalize(ts)

      # generator algorithm took an interaction matrix as input
      if(Algorithm == "ricker" || Algorithm == "soc" || Algorithm == "glv"){
        source.expId = expId
        interactionmatrix.folder=input.settings.expId.folder
        Agenerator=TRUE
        # interaction matrix for current experiment was read from another experiment
        if(!is.na(Input_experiment_identifier)){
          source.expId=Input_experiment_identifier
          source.expId.folder=paste(source.expId,"settings",sep="_")
          interactionmatrix.folder=paste(input.settings.folder,source.expId.folder,sep="/")
        }
        A.name=paste(source.expId,"interactionmatrix.txt",sep="_")
        input.path.A=paste(interactionmatrix.folder,A.name,sep="/")
        print(paste("Reading original interaction matrix from:",input.path.A,sep=" "))
        A=read.table(file=input.path.A,sep="\t",header=FALSE)
        A=as.matrix(A)
      } # end generator algorithm provided interaction matrix

      # read predicted interaction matrix
      pred.interactionmatrix.name=paste(expId,"_timeseries_Best.txt",sep="")
      pred.interactionmatrix.path=paste(pred.expId.folder,pred.interactionmatrix.name,sep="/")
      print(paste("Reading predicted interaction matrix from:",pred.interactionmatrix.path,sep=" "))
      Apred=read.table(file=pred.interactionmatrix.path,header=FALSE)
      Apred=as.matrix(Apred)

      if(nrow(Apred) != nrow(ts)){
        stop("The predicted interaction matrix does not include all species in the original time series!")
      }

      if(Agenerator==TRUE){
        N=ncol(A)
        corAwithApred=sum(diag(cor(A,Apred)))/N
        print(paste("Average correlation between columns of the original and the estimated interaction matrix:",corAwithApred))
        resultStr=paste(resultStr,"Mean_correl_A_Apred=",corAwithApred,"\n", sep="")
      }

      if(output.folder != ""){
        out.limitsqual.name=paste(expId,"limitsquality.pdf",sep="_")
        out.limitsqual.path=paste(output.subfolder, out.limitsqual.name,sep="/")
        pdf(out.limitsqual.path, onefile=TRUE)
      }

      if(topN > 0){
        sorted=sort(apply(ts,1,sum),decreasing=TRUE,index.return=TRUE)
        # remove top-abundant taxa
        keep=setdiff(1:nrow(ts),sorted$ix[1:topN])
        Apredmodif=Apred[keep,keep]
        tsmodif=ts[keep,]
      }else{
        Apredmodif=Apred
        tsmodif=ts
      }
      outqual=plotLimitsQuality(oriTS=tsmodif, A=Apredmodif, noSchur=TRUE, ignoreExplosion = TRUE)
      minqual=min(outqual$meancrosscor, na.rm=TRUE)
      maxqual=max(outqual$meancrosscor, na.rm=TRUE)
      meanqual=mean(outqual$meancrosscor, na.rm=TRUE)
      minautocor=min(outqual$meanautocor1, na.rm=TRUE)
      maxautocor=max(outqual$meanautocor1, na.rm=TRUE)
      meanautocor=mean(outqual$meanautocor1, na.rm=TRUE)
      # determine the slope pf the auto- and cross-correlation values
      linreg1=lm(outqual$meancrosscor~outqual$taxonnum)
      slopequal=linreg1$coefficients[2]
      sum1=summary(linreg1)
      pvalqual=1-pf(sum1$fstatistic[1], sum1$fstatistic[2], sum1$fstatistic[3])

      linreg2=lm(outqual$meanautocor1~outqual$taxonnum)
      slopeautocor=linreg2$coefficients[2]
      sum2=summary(linreg2)
      pvalautocor=1-pf(sum2$fstatistic[1], sum2$fstatistic[2], sum2$fstatistic[3])

      print(paste("Minimum prediction quality:",minqual))
      print(paste("Maximum prediction quality:",maxqual))
      resultStr=paste(resultStr,"Minimum_pred_qual=",minqual,"\n", "Maximum_pred_qual=",maxqual,"\n","Mean_pred_qual=", meanqual, "\n","Slope_pred=",slopequal,"\n", "Pval_slope_pred=", pvalqual, "\n", sep="")
      resultStr=paste(resultStr,"Minimum_autocor1_qual=",minautocor,"\n", "Maximum_autocor1_qual=",maxautocor,"\n","Mean_autocor1_qual=", meanautocor, "\n", "Slope_autocor1=", slopeautocor, "\n", "Pval_slope_autocor1=", pvalautocor, "\n", sep="")

      if(output.folder != ""){
        dev.off()
      }

    } # end interaction matrix generated by predictor

    # comparison of time series
    tend=ncol(tspred)
    if(length(keep) > 0){
      tspred=tspred[keep,]
      ts=ts[keep,]
    }
    Rcross=mean(diag(cor(t(ts[,1:tend]),t(tspred[,1:tend]))))
    print(paste("Mean cross-correlation between original and predicted time series",Rcross))
    resultStr=paste(resultStr,"Mean_cross_correl_ori_pred_ts=",Rcross,"\n", sep="")

    if(output.folder != ""){
      resultStr=paste(resultStr,"Top_abundant_species_omitted=",topN,"\n", sep="")
      resultStr=paste(resultStr,"steps=",ncol(ts),"\n", sep="")
      # add settings (omit N, klemm, tweak, diagonal value and clique size, which are constants)
      if(Algorithm == "hubbell"){
        resultStr=paste(resultStr,"deathrate_Hubbell=",deathrate_Hubbell,"\n", sep="")
        resultStr=paste(resultStr,"immigration_rate_Hubbell=",immigration_rate_Hubbell,"\n", sep="")
      }else{
        resultStr=paste(resultStr,"deathrate_Hubbell=NA","\n", sep="")
        resultStr=paste(resultStr,"immigration_rate_Hubbell=NA","\n", sep="")
      }
      resultStr=paste(resultStr,"I=",I,"\n", sep="")
      resultStr=paste(resultStr,"init_abundance_mode=",init_abundance_mode,"\n", sep="")
      resultStr=paste(resultStr,"sigma=",sigma,"\n", sep="")
      resultStr=paste(resultStr,"connectance=",connectance,"\n", sep="")
      resultStr=paste(resultStr,"Algorithm=",Algorithm,"\n", sep="")
      resultStr=paste(resultStr,"Requested_positive_edge_percentage_of_interaction_matrix=",Requested_positive_edge_percentage_of_interaction_matrix,"\n", sep="")
      resultStr=paste(resultStr,"Sampling_frequency=",Sampling_frequency,"\n", sep="")

      result.file.name=paste(expId,"quality.txt",sep="_")
      result.file.path=paste(output.subfolder, result.file.name, sep="/")
      write(resultStr,file=result.file.path)
    }

  } # end loop experiment identifiers

}
