######################################################
# DETECT WHETHER OR NOT THE TIME SERIES UNDERLYING DYNAMICS CAN BE UNDERSTOOD IN TERMS OF A RICKER MODEL
######################################################



rm(list = ls())

# the time series to analyse should be located in "folder_name" and 
# should be called xx_name_file where xx is a number

folder_name <-"/Users/sdebuyl/timeseries/"
name_file<-"_timeseries" 

#choose time series to analyze
timeseries.list=c(1) #
#choose sampling method (ie, choose max number of species kept, time skip, length kept)
Nmax= 60              # maximal number of species to include in the analysis 
subsambpling=FALSE   # set to TRUE to look only at time points [1501:1600]

# each column of the timeseries is one species. 

library(ggplot2)
library(geigen)
library(MASS)
library(matrixStats)
library(miscTools)
library(gridExtra)

source("apply_limits.R")



#loop over the different time series to analyze
for(ll in timeseries.list){
  print(ll)
  
  #time series location 
  name_file_with_nbr=paste(ll,name_file,sep="") #name of the folder where this matrix is stored 
  file.path= paste(folder_name,name_file_with_nbr,sep="") #full name of the path to this folder 51_sliced_timeseries.txt
  
  #create a directory to save results (copy the time series in this file too)
  dir.create(file.path, showWarnings = FALSE)
  file.copy(paste(folder_name,name_file_with_nbr,'.txt',sep=""),file.path)
  
  #load time series
  R<-t(read.table(paste(file.path,'/',name_file_with_nbr,'.txt',sep="")))
  R[R<0]<-0
  sd=dim(R)
  N=sd[2]
  tend=sd[1]
  tmax=tend
  
  tskip.list=c(1)       # j-loop  (if we choose tskip.list=c(1), we don't look for sub-sampling)
  tend.max.list=c(tend) # m-loop  (if only one value, we don't look at the effect of shortening the ts)
  
  print(paste("N is ",N," and tend is ",tmax,sep=""))

  if(subsambpling==TRUE){
    if(tend<3000) next
    R<-R[1501:1900,]  #R<-R[1:100,]
    sd=dim(R)
    N=sd[2]
    tmax=sd[1]
  }
  
  #deal with too short time series
  if(N<Nmax){
    print(paste(ll," N is too small"))
    Nmax= N
    next
  }
  
  # if(tskip.list[length(tskip.list)]*tend.max.list[length(tend.max.list)]>tend){
  #   tskip.list=c(1)         # j
  #   tend.max.list=c(round(tend/3),round(tend*2/3),tend) # m
  #   print(paste(ll," tend is too small"))
  #   next
  # }
  
  allindices<-seq(1,N)
  #initiate list of data frame that will contain 
  correlation.coefficients<-list()  # correlation coefficients between data and predicted data
  auto.correlation.coefficients<-list()  # auto-correlation coefficients (time series)
  corAB=0 #to keep correlation between original and inferred interaction matrix for each cases
  
  ######################################################
  #loop over the different sampling methods
  ######################################################
  

  for (j in 1:length(tskip.list)) {
    for (m in 1:length(tend.max.list)) {
     
      timepts <- seq(1,tmax,by = tskip.list[j]) # sampling of the time series
      Rtemp <- R[timepts,1:N]
      if (tend.max.list[m] > length(timepts)) next
      Rtemp <- Rtemp[1:tend.max.list[m],] # cutting the time series to tend value
      sd = dim(Rtemp)
      
      namefile.specific = paste(ll,"_ts_N_",Nmax,"_skip_",tskip.list[j],'_tmax_',dim(Rtemp)[1],sep ="")
      file.path.specific = paste(file.path,"/",namefile.specific,sep ="")
      dir.create(file.path(file.path.specific), showWarnings = FALSE)
      CC<-apply_limits(Rtemp,file.path.specific,Nmax = Nmax, tmax = tmax,percOKlist = c(.9,.7,.5,.4,.3,.2,.1,0),allindices =allindices)
      
      #import data generated by limits (useless in this file but could be useful)
      corr_table = CC[[2]]
      Best = CC[[1]]
      list.species.ordered=CC[[3]]
      
      
    }#end of m loop
  }#end of j loop
  
} #end of "l" loop








